name       : openspades
version    : 0.1.0
release    : 1
source     :
    - https://github.com/yvt/openspades/archive/v0.1.0.tar.gz : e5941cb9121ac33ecfd7b7309451b1322f78cb6c52ed534b900ccca0b8a73298
    - https://github.com/yvt/openspades-paks/releases/download/r32/OpenSpadesDevPackage-r32.zip : 167beca91d28129d1817ba140b21852a7d02363280d310168c722691b7317834
license    : 
    - GPL-3.0 # Sources
    - OpenSpades Non-GPL PAK License # MIT lookalike https://github.com/yvt/openspades-paks/blob/master/Nonfree/LICENSE.md
component  : games.action
summary    : OpenSpades is a compatible client of Ace of Spades 0.75.
description: |
    OpenSpades is a compatible client of Ace of Spades 0.75.
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(freealut)
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(libcurl)
    - pkgconfig(opusfile)
    - pkgconfig(xft)
    - imagemagick
    - unzip
    - xdg-utils
setup      : |
    # Use a local OpenSpadesDevPackage instead of pulling from network
    mkdir devpackage
    cd devpackage
    unzip $sources/OpenSpadesDevPackage-r32.zip
    mv Nonfree/* ../Resources/
    mv OfficialMods ../
    cd $workdir
    sed -i '4,12d' Resources/CMakeLists.txt # Ensure we're not running their downloadpak script
    %cmake -DOPENSPADES_INSTALL_RESOURCES=share/openspades/Resources \
           -DOPENSPADES_INSTALL_BINARY=bin \
           -DOPENSPADES_INSTALL_LIBS=lib64/openspades .
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/share/doc
