name       : openspades
version    : 0.1.1c
release    : 2
source     :
    - https://github.com/yvt/openspades/archive/v0.1.1c.tar.gz : e51d6b9422aef149944d7f6a28a284291fb322a025b3fee8bd2cc9da622a73c7
    - https://github.com/yvt/openspades-paks/releases/download/r33/OpenSpadesDevPackage-r33.zip : 0927dc323a0b3aba0ee8d1d68d6b544b00fe654740fead6d1faad37aac77a2ad
license    : 
    - GPL-3.0 # Sources
    - OpenSpades Non-GPL PAK License # MIT lookalike https://github.com/yvt/openspades-paks/blob/master/Nonfree/LICENSE.md
component  : games.action
summary    : OpenSpades is a compatible client of Ace of Spades 0.75.
description: |
    OpenSpades is a compatible client of Ace of Spades 0.75.
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(freealut)
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(libcurl)
    - pkgconfig(opusfile)
    - pkgconfig(xft)
    - imagemagick
    - unzip
    - xdg-utils
setup      : |
    # Use a local OpenSpadesDevPackage instead of pulling from network
    mkdir devpackage
    cd devpackage
    unzip $sources/OpenSpadesDevPackage-r33.zip
    mv Nonfree/* ../Resources/
    mv OfficialMods/* ../Resources/
    cd $workdir
    sed -i '4,12d' Resources/CMakeLists.txt # Ensure we're not running their downloadpak script
    %cmake -DOPENSPADES_INSTALL_RESOURCES=share/openspades/Resources \
           -DOPENSPADES_INSTALL_BINARY=bin \
           -DOPENSPADES_INSTALL_LIBS=lib64/openspades .
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/share/doc
